### PR TITLE
Properly calculate the index of array elements during recreation.

### LINKED ISSUE #300: Incorrect `ClaimPath` for array elements when decoys are used
When recreating the claims of an SD-JWT, if the payload contains a `JsonArray` that contains Decoys, the `ClaimPaths` of the actual Array Elements are not properly calculated.
The current implementation always increments the array index, disregarding the fact that Decoys might have been employed in the array. [source](https://github.com/eu-digital-identity-wallet/eudi-lib-jvm-sdjwt-kt/blob/main/src/main/kotlin/eu/europa/ec/eudi/sdjwt/RecreateClaims.kt#L225)

For instance the following with the following `JsonArray` as input:
```json
{
    "array": [
        "..decoy..",
        "..decoy..",
        "value",
        "..decoy.."
    ]
}
```

`value` is assigned the `ClaimPath` `['array', 2]`, when it should have been `['array', 0]`.

### PR DESCRIPTION
**Pull request by dzarras**
Fixes #300

### CODE REVIEW

File: src/main/kotlin/eu/europa/ec/eudi/sdjwt/RecreateClaims.kt [hunk 1]
```diff
@@ -225,11 +225,12 @@ private class DiscloseObject(
     private fun discloseArray(
         currentPath: ClaimPath,
         jsonArray: JsonArray,
-    ): JsonArray =
-        jsonArray
-            .zip(0..<jsonArray.size)
-            .mapNotNull { (element, index) -> discloseArrayElement(currentPath, element, index) }
+    ): JsonArray {
```
Comment (babisRoutis) [inline src/main/kotlin/eu/europa/ec/eudi/sdjwt/RecreateClaims.kt:228]: @dzarras 
Personally I find somehow confusing the `?.also { }` which changes a state variable outside the the lambda.
Perhaps, a more imperative implementation gives a more clear view

```kotlin
buildJsonArray {
    var index = 0
    jsonArray.forEach { element ->
        discloseArrayElement(currentPath, element, index)
            ?.let { add(it); index++ }
    }
}
```

**Review by babisRoutis — DISMISSED** [review]
@dzarras Approved. Just a minor comment for your consideration
