### PR TITLE
Fix verification of SD-JWT VCs signed using EdDSA/OctetKeyPair

### LINKED ISSUE #229: Validating an EdDSA signed SD-JWT fails
I noticed that when using Ed25519 keys in their JWK form (`com.nimbusds.jose.jwk.OctetKeyPair`) the key selector does not find the key in question and the verification of the SD-JWT fails with an `InvalidJwt` error.

The source of the issue seems to be that nimbus `JWSVerificationKeySelector` does not work well with asymmetric keys that are not `ECKey` or `RSAKey` because when we get a match for a JWT that represents a OKP key (Ed25519 in our case), converting the key to Java keys via `com.nimbusds.jose.jwk.KeyConverter.toJavaKeys` just silently ignores the key in question.

I do realize that this is mostly in the nimbus library but as sdjwt-kt relies on this logic I wondered if you ever had a similar issue, or if you have some advice on how to approach solving it.

Thanks!

### PR DESCRIPTION
**Pull request by dzarras**
The main problem comes from Nimbus `DefaultJWTProcessor` which when processing a signed JWT :
- Requires all JWKs representing an issuer's pub keys to be representing a `java.security.Key`, yet
- `OctetKeyPair` doesn't implement the above conversion.

Solution provided by this PR, is to replace in the context of `sd-jwt-vc` verification the `DefaultJWTProcessor` with a custom processor, that 
- accepts a list of issuer pub keys (extracted by the sd-jwt-vc discovery process)
- instantiates an appropriate verifier (in the ED case there is Nimbus `Ed25519Verifier` that accepts the JWK)
- considers dig sig as valid, on the first verifier that succeeds.
- All other checks (for `typ`, claim set content etc, are preserved)

The above solution requires that caller includes on the class path Tink library, on its own.

Closes #229

### CODE REVIEW

**Comment by dzarras** [comment]
@babisRoutis Should we also promote Google's Tink to a runtime dependency?

File: src/main/kotlin/eu/europa/ec/eudi/sdjwt/vc/SdJwtVcVerifier.kt [hunk 1]
```diff
@@ -272,14 +279,78 @@ internal fun keySource(jwt: SignedJWT): SdJwtVcIssuerPublicKeySource? {
...
 }
 
-private fun sdJwtVcProcessor(keySelector: JWSKeySelector<SecurityContext>): JWTProcessor<SecurityContext> =
-    DefaultJWTProcessor<SecurityContext>().apply {
+const val SD_JWT_VC_TYPE = "vc+sd-jwt"
+
+/**
+ * Custom [DefaultJWTProcessor] implementation with support for [OctetKeyPair].
+ */
+private class SdJwtVcJwtProcessor<C : SecurityContext>(
```
Comment (babisRoutis) [inline src/main/kotlin/eu/europa/ec/eudi/sdjwt/vc/SdJwtVcVerifier.kt:287]: Can you please extract the class in its own file, with `internal` scope

**Review by babisRoutis — APPROVED** [review]
@dzarras LGTM

Just a minor comment, to externalize on its file the custom processor and document (in the comments) why it was created.

**Comment by babisRoutis** [comment]
> @babisRoutis Should we also promote Google's Tink to a runtime dependency?

I would say, no.

Instead we can document in the README, that the caller must include tink on its own, when dealing with ED.
I was thinking a simple knit example pointing to the test you created with the above disclaimer.

**Comment by nemqe** [comment]
@babisRoutis I had a quick look LGTM

I could checkout this PR and try it out in our codebase if would find that valuable?

**Review by babisRoutis — APPROVED** [review]

**Comment by babisRoutis** [comment]
> @babisRoutis I had a quick look and it LGTM.
> 
> I also checked-out the PR and tried it locally with the EdDSA signature - works like a charm.
> 
> Many thanks for the quick fix!

@nemqe  Thanks for the additional checks.
